### ISSUE TITLE
my.dabase.com

### ISSUE THREAD

**Issue by kaihendry** [HazeWatchApp/apims_data#1]
Could you please link http://my.dabase.com/ with the source here: https://github.com/kaihendry/pjhaze

Do you document exactly how the apims_data was fetch and pushed to github somewhere? :)

**Comment by nazroll** [comment]
@kaihendry we have a secret scraper hahahaha

**Comment by kaihendry** [comment]
http://jbsg.dabase.com/ is another

**Comment by nazroll** [comment]
@kaihendry i think there is an error to the 2nd link.

![screen shot 2015-11-18 at 02 26 53](https://cloud.githubusercontent.com/assets/33108/11220639/e949cb82-8d9b-11e5-910d-f037d52e6788.png)

**Comment by kaihendry** [comment]
Singapore PSI API seems down for the last couple of days for me.
https://twitter.com/kaihendry/status/666292048194985984

I did move servers recently. Could just be me....

**Comment by nazroll** [comment]
@kaihendry ok cool. i'm just going to leave that one out for the time being. the first link is in the README.md. We're working on a new website, so it will be listed there eventually.
